name: breathe-paper
channels:
  - conda-forge
dependencies:
  - pip
  - matplotlib
  - Pillow
  - torch
  - SoundFile
  - pandas
  - learn
  - progressbar
  - torchaudio
  - torchvision
  - tqdm
  - scikit
  - requests
  - librosa
  - numpy
