[tool.poetry]
name = "breathe"
version = "0.1.0"
description = ""
authors = ["Theodore Aptekarev <aptekath@bgu.ac.il>"]

[tool.poetry.dependencies]
python = "~3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
